### ISSUE TITLE
Problems with ButtonEditor_simple_demo.py using qt 

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1072] opened 2020-07-24 20:09 UTC
When I run this demo on qt when I click the button the counter doesn't increment until I click somewhere outside of the GUI.  For wx the click counter instantly increments on every click.

**Comment by kitchoi** [comment] 2020-07-29 08:38
Hi @aaronayres35 
Thank you for the report.
If that's ok, could you please include the package versions you used in your environment? e.g. the output of `pip list` on the command line.
I am asking because we have had many issues that are only reproducible on certain combination of Qt version or platform or PySide-vs-PyQt. Such information will be helpful for diagnosing issues. Thank you!

More recently we also are seeing more compatibility issues between OSX and Qt to do with redrawing UIs. This particular issue reminds me of #913, which is only seen on OSX and certain versions of Qt (see description there).

**Comment by aaronayres35** [comment] 2020-07-29 12:56
> Hi @aaronayres35
> Thank you for the report.
> If that's ok, could you please include the package versions you used in your environment? e.g. the output of `pip list` on the command line.

Hi @kitchoi , yes definitely, here is the output from pip list:
<details>

```
(qt-env)~/Desktop/traitsui/traitsui/examples/demo/Standard_Editors aayres  (fix-progress-example) $ pip list
Package                       Version      Location                      
----------------------------- ------------ ------------------------------
alabaster                     0.7.10       
appdirs                       1.4.3        
apptools                      4.5.0        
babel                         2.6.0        
certifi                       2018.11.29   
chaco                         4.8.0        
chardet                       3.0.4        
configobj                     5.0.6        
coverage                      4.3.4        
distribute-remove             1.0.0        
docutils                      0.16         
enable                        4.8.1        
enthought-sphinx-theme        0.6.2        
fonttools                     3.29.1       
freetype                      2.10.0       
h5py                          2.10.0       
harfbuzz                      2.6.4        
hdf5                          1.10.5       
icu4c                         50.2         
idna                          2.5          
imagesize                     0.7.1        
jinja2                        2.10.1       
kiwisolver                    1.0.1        
libjpeg                       7.0          
liblzma                       5.2.4        
libopenjpeg                   2.3.0        
libpng                        1.6.36       
libtiff                       4.0.10       
libxml2                       2.9.7        
libxslt                       1.1.30       
markupsafe                    1.1.1        
MKL                           2018.0.3     
nose                          1.3.7        
numexpr                       2.6.9        
numpy                         1.17.4       
packaging                     16.8         
pandas                        0.25.3       
pillow                        5.2.0        
pip                           20.0.2       
pyface                        7.1.0.dev61  
Pygments                      2.2.0        
pyparsing                     2.2.0        
PyQt5                         5.14.2       
PyQt5-sip                     12.7.2       
pytables                      3.5.1        
python-dateutil               2.8.0        
pytz                          2018.9       
Qt                            5.12.6       
requests                      2.21.0       
setuptools                    41.6.0       
six                           1.11.0       
snowballstemmer               1.2.1        
sphinx                        2.3.1        
sphinxcontrib-applehelp       1.0.1        
sphinxcontrib-devhelp         1.0.1        
sphinxcontrib-htmlhelp        1.0.2        
sphinxcontrib-jsmath          1.0.1        
sphinxcontrib-qthelp          1.0.2        
sphinxcontrib-serializinghtml 1.1.3        
sphinxcontrib-websupport      1.1.0        
traits                        6.1.0        
traitsui                      7.1.0.dev205 /Users/aayres/Desktop/traitsui
urllib3                       1.25.3  
```

</details>
Also I'm on OSX

**Comment by kitchoi** [comment] 2020-07-29 13:07
Thank you @aaronayres35

**Comment by aaronayres35** [comment] 2020-07-30 20:53
@kitchoi I believe this is basically the same issue as mentioned on #913 
Following Mark's suggestion and adding 
```
def _click_counter_changed(self):
        from pyface.qt.QtGui import QApplication
        app = QApplication.instance()
        app.processEvents()
```
seemed to fix thee problem.  However, I wanted to check with you of how we should handle this for the demo.  The code is clearly a work around and feels out of place for the purpose of the demo.  Should I simply add a comment explaining why it is necessary and reference the issue?

**Comment by kitchoi** [comment] 2020-07-31 08:18
I agree this workaround is out-of-place for the demo. Such workarounds are not scalable and should not be seen as the expected thing to do.
Adding a comment referencing explaining the awkwardness with Qt5 and OSX sounds reasonable to me.

**Comment by kitchoi** [comment] 2020-07-31 14:38
Closing this as a duplicate of #913

**Closed** 2020-07-31 14:39 UTC
Labels: component: demo
