### ISSUE TITLE
Buttons not updated according to their enabled_when definition

### ISSUE THREAD

**Issue by robertopreste** [enthought/traitsui#1529] opened 2021-03-03 15:02 UTC
[Seemingly related to / possible duplicate of #913] 

A simple example:

```python
from traits.api import Bool, Button, Enum, HasTraits, Instance, observe
from traitsui.api import HGroup, Item, ModelView, UItem, View


class BaseModel(HasTraits):

    activate_item_1 = Bool(False)

    activate_item_2 = Bool(False)    


class MainModel(HasTraits):

    base_model = Instance(BaseModel)

    def _base_model_default(self):
        return BaseModel()


class MainView(ModelView):

    model = Instance(MainModel)

    button_1 = Button("Button 1")

    button_2 = Button("Button 2")

    switch = Enum("Scenario 1", "Scenario 2")

    @observe("switch")
    def update_scenario(self, event):
        if self.switch == "Scenario 1":
            self.model.base_model.activate_item_1 = True
            self.model.base_model.activate_item_2 = False
        else:
            self.model.base_model.activate_item_1 = False
            self.model.base_model.activate_item_2 = True

    def default_traits_view(self):
        return View(
            Item("switch"),
            HGroup(
                Item("model.base_model.activate_item_1"),
                Item("model.base_model.activate_item_2"),
            ),
            HGroup(
                UItem("button_1",
                      enabled_when="model.base_model.activate_item_1"),
                UItem("button_2",
                      enabled_when="model.base_model.activate_item_2"),
            )
        )


if __name__ == '__main__':
    my_model = MainModel()
    my_view = MainView(model=my_model)
    my_view.configure_traits()
```

Buttons should be enabled/disabled according to the two checkboxes. When selecting “Scenario 2" from the dropdown menu and checking/unchecking one of the checkboxes, the buttons do not update as expected (unless some other interaction on the UI is performed).

Tests fail as well, for example:

```python
class TestMyView(unittest.TestCase):

    def setUp(self):
        self.tester = UITester()
        self.model = MainModel()
        self.view = MainView(model=self.model)

    def test_buttons(self):
        with self.tester.create_ui(self.view) as ui:
            switch = self.tester.find_by_name(ui, "switch")
            scenario_2 = switch.locate(Index(1))
            scenario_2.perform(MouseClick())
            # Uncheck second item
            checkbox_2 = self.tester.find_by_name(ui, "activate_item_2")
            checkbox_2.perform(MouseClick())
            self.assertFalse(checkbox_2.inspect(IsChecked()))
            button_1 = self.tester.find_by_name(ui, "button_1")
            self.assertFalse(button_1.inspect(IsEnabled()))
            button_2 = self.tester.find_by_name(ui, "button_2")
            self.assertFalse(button_2.inspect(IsEnabled()))
```

fails at the last assertion (that button should be disabled, but it’s not).

**Comment by rahulporuri** [comment] 2021-03-03 15:28
I am able to reproduce this behavior on windows + python 36 + pyqt5 - and here is the behavior that I observed

![why-traitsui-why](https://user-images.githubusercontent.com/1926457/109828960-068dcf80-7c35-11eb-840c-3ed6deddd59e.gif)

**Comment by corranwebster** [comment] 2021-03-03 15:51
IIRC #913 was MacOS-specific.

**Comment by aaronayres35** [comment] 2021-03-05 22:35
ref: #833 

See code:
https://github.com/enthought/traitsui/blob/d7315b47e3b1818db28048c047c42a07bbb82b2a/traitsui/ui.py#L431-L441

**Comment by aaronayres35** [comment] 2021-03-09 22:48
I believe this is effectively the same issue as #833.  Because the `BaseModel` instance is not in the context, it doesn't get an anytrait changed listener hooked up to it to call `_evaluate_when` (see code in comment above). Thus, clicking a checkbox doesn't trigger an `_evaluate_when` call, so no update is made.  Doing something else on the UI will end up changing some trait on the `MainView` or `MainModel` (the two things in the context by default) and then things will be updated accordingly. Adding the `BaseModel` to the trait_context fixes this.
From slack discussion it looks like that suggestion (originally made in 833) was used to resolve the downstream issue.

I am going to close this issue as a duplicate.

I think we will likely want to open a separate issue regarding better documentation for this use case as we have seen it come up a couple times now. Assuming we don't want to do any sort of refactor which, based off https://github.com/enthought/traitsui/issues/833#issuecomment-631573733, it appears we probably would not want to do.

The only other approach I could think of is that in the code in the above comment, we listen to not only any trait on the `object` in the context, but potentially nested traits as well (`observe` could be useful to do that).  This has potential to get very ugly fast though, as we could end up listening to a length list of traits, so probably won't end up working out.  At least with that approach we could still preserve the behavior of passing python expressions in to `enabled_when`, the expressions would just be evaluated (potenitally _wayyyy_) more frequently.  When trying to wrap my head around this code I realized that already the expressions get evaluated many more times than you would expect.  For example you click the `switch` combobox and change a value you might think thats one trait change, so `_evaluate_when` should be called once, but in actuality I saw 6 trait changes and a corresponding 6 calls to `_evaluate_when`

**Closed** 2021-03-10 00:53 UTC
Labels: type: bug
