### ISSUE TITLE
Multi-date section of date_editor_demo is broken

### ISSUE THREAD

**Issue by achabotl** [enthought/traitsui#419] opened 2018-02-12 23:15 UTC
Clicking on any date in the `multi_date` section of `Advanced/Date_editor_demo.py` fails with the following traceback. 

```python
Traceback (most recent call last):
  File "/Users/achabot/Library/Enthought/Canopy/edm/envs/User/lib/python2.7/site-packages/traitsui/qt4/date_editor.py", line 157, in update_object
    self.value = datetime.date(year, month, day)
  File "/Users/achabot/Library/Enthought/Canopy/edm/envs/User/lib/python2.7/site-packages/traitsui/editor.py", line 254, in _set_value
    self.ui.do_undoable( self.__set_value, value )
  File "/Users/achabot/Library/Enthought/Canopy/edm/envs/User/lib/python2.7/site-packages/traitsui/ui.py", line 715, in do_undoable
    action( *args, **kw )
  File "/Users/achabot/Library/Enthought/Canopy/edm/envs/User/lib/python2.7/site-packages/traitsui/editor.py", line 267, in __set_value
    method( self.ui.info, self.object, name, value )
  File "/Users/achabot/Library/Enthought/Canopy/edm/envs/User/lib/python2.7/site-packages/traitsui/handler.py", line 269, in setattr
    setattr( object, name, value )
  File "/Users/achabot/Library/Enthought/Canopy/edm/envs/User/lib/python2.7/site-packages/traits/trait_types.py", line 2339, in validate
    self.error( object, name, value )
  File "/Users/achabot/Library/Enthought/Canopy/edm/envs/User/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'multi_date' trait of a DateEditorDemo instance must be a list of items which are a date or None, but a value of datetime.date(2018, 2, 7) <type 'datetime.date'> was specified.
```

Using:

```
(User)$ python
Enthought Deployment Manager -- https://www.enthought.com
Python 2.7.13 |Enthought, Inc. (x86_64)| (default, Mar  2 2017, 08:20:50)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by corranwebster** [comment] 2018-02-22 09:32
Works OK with WxPython backend, so this is a Qt problem.

**Comment by corranwebster** [comment] 2018-02-22 09:52
And digging a bit further, the underlying `QCalendarWidget` does not support multi-select.  Not a lot we can do to fix other than writing a custom calendar widget, which is not on the cards.

Could give better feedback about what is not supported, though.

**Comment by midhun-pm** [comment] 2019-12-26 14:32
I can't seem to reproduce this behavior. Tried it with Qt back-end and python2.7.13

**Comment by rahulporuri** [comment] 2021-04-27 05:28
closing as i cant reproduce this with python 3.6 and pyqt5.

**Closed by rahulporuri** 2021-04-27 05:28 UTC
