### ISSUE TITLE
ModuleNotFoundError: No module named 'pyface.base_toolkit' 

### ISSUE THREAD

**Issue by lucascbarbosa** [enthought/traitsui#1659] opened 2021-05-10 19:12 UTC
I'm having a problem importing `import traitsui.api`, it raises the following error:
```
>>> import traitsui.api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lucas\anaconda3\envs\deeplearn\lib\site-packages\traitsui\api.py", line 21, in <module>
    from .basic_editor_factory import BasicEditorFactory
  File "C:\Users\lucas\anaconda3\envs\deeplearn\lib\site-packages\traitsui\basic_editor_factory.py", line 24, in <module>
    from .editor_factory import EditorFactory
  File "C:\Users\lucas\anaconda3\envs\deeplearn\lib\site-packages\traitsui\editor_factory.py", line 33, in <module>
    from .toolkit import toolkit_object
  File "C:\Users\lucas\anaconda3\envs\deeplearn\lib\site-packages\traitsui\toolkit.py", line 26, in <module>
    from pyface.base_toolkit import Toolkit, find_toolkit
ModuleNotFoundError: No module named 'pyface.base_toolkit'
```

**Comment by rahulporuri** [comment] 2021-05-11 03:09
hey @lucascbarbosa , this looks like a duplicate of https://github.com/enthought/pyface/issues/941 and solving that pyface issue will hopefully solve this issue. Let's move the discussion to the pyface issue - and i'll close this issue once we reach a conclusion.

**Closed** 2021-05-18 10:56 UTC
