### ISSUE TITLE
traitsui crashes Python 3 when Toggle axes indicator after Mayavi 4.7.0 rendering

### ISSUE THREAD

**Issue by mprogram** [enthought/traitsui#582] opened 2019-07-11 09:05 UTC
When pressing `Toggle axes indicator` in Mayavi2 after final image was obtained, as shown in the enthought/mayavi/issues/798 , `traitsui`crashes Python 3:
`$ env QT_API=pyside2 ETS_TOOLKIT=qt4 mayavi2`
``` python
ERROR|2019-07-11 11:52:44,492|Exception occurred in traits notification handler for object: <mayavi.filters.poly_data_normals.PolyDataNormals object at 0x7f2751df3e60>, trait: name, old value: PolyDataNormals, new value: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python3/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python3/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 139806876099512
ERROR|2019-07-11 11:52:44,535|Exception occurred in traits notification handler for object: <mayavi.modules.surface.Surface object at 0x7f274bc2cd00>, trait: name, old value: Surface, new value: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/usr/lib/python3/dist-packages/traits/trait_notifiers.py", line 695, in dispatch
    handler(*args)
  File "/usr/lib/python3/dist-packages/traitsui/tree_node.py", line 1899, in wrapped_listener
    return listener(node, name, new)
  File "/usr/lib/python3/dist-packages/traitsui/qt4/tree_editor.py", line 1618, in _label_updated
    for name2, nid in self._map[id(object)]:
KeyError: 139806876099512
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = python3.6 path = /usr/bin pid = 32090
KCrash: Arguments: /usr/bin/python3.6 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
```

**Comment by corranwebster** [comment] 2019-07-11 11:14
This is a duplicate of #576.  I am going to close.

**Closed by corranwebster** 2019-07-11 11:14 UTC
