### ISSUE TITLE
Numpy tabular editor demo has font issue

### ISSUE THREAD

**Issue by cfarrow** [enthought/traitsui#4] opened 2011-06-18 23:05 UTC
When running the demo at examples/demo/Advanced/NumPy_array_tabular_editor_demo.py I get the following exception when hovering over the table.

OnGetItemAttr
    attr.SetFont( font )
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/wx/_controls.py", line 4163, in SetFont
    return _controls_.ListItemAttr_SetFont(_args, *_kwargs)
TypeError: in method 'ListItemAttr_SetFont', expected argument 2 of type 'wxFont const &'

Running from master on OSX 10.6.

**Comment by rahulporuri** [comment] 2021-04-27 04:37
closing as I can't reproduce this at the moment.

**Closed by rahulporuri** 2021-04-27 04:37 UTC
Labels: component: examples
