### ISSUE TITLE
importing editors.enum_editor creates locale side effect 

### ISSUE THREAD

**Issue by massich** [enthought/traitsui#382] opened 2017-08-04 15:13 UTC
Running with mne-python tests I encountered a locale side effect due to a mayavi import which boils down to traitsui. The following MWE reproduce the side effect. 
 
```sh
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import locale
>>> locale.nl_langinfo(locale.MON_1)
'January'
>>> import traitsui.editors.enum_editor
>>> locale.nl_langinfo(locale.MON_1)
'janvier'
```
Any ideas?

**Comment by Eric89GXL** [comment] 2017-08-04 15:17
I at least do not have this error:
```
Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import locale
>>> locale.nl_langinfo(locale.MON_1)
'January'
>>> import traitsui.editors.enum_editor
>>> locale.nl_langinfo(locale.MON_1)
'January'
```
Maybe it has to do with the default language on the system, which for me would be En-US and thus wouldn't change?

**Comment by corranwebster** [comment] 2017-08-04 15:57
That's certainly curious.  There's nothing particularly date or locale related immediately in the `enum_editor` module, but your first import of anything from TraitsUI will pull in a lot of stuff, and in particular will import toolkit code.

To help diagnose:

- what backend are you using: Wx or Qt?
- is this effect limited to `enum_editor` or do you see it elsewhere? In particular, do you see the same effect when you do `import pyface.api`? If you see it there, what happens when you import Wx or Qt without TraitsUI?

My current best guess is that this side-effect is coming from Wx or Qt, but there is a lot of other code which TraitsUI which could also be responsible.

**Comment by agramfort** [comment] 2017-08-04 16:12
FYI I cannot replicate on my system.

**Comment by massich** [comment] 2017-08-04 16:16
@corranwebster `import pyface.api` has the same effect (it changes from _'January'_ to _'Javiner'_)
@Eric89GXL these are my locals:
```sh
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```
which do you have?

**Comment by massich** [comment] 2017-08-04 16:17
And this is the backend

```sh
In [1]: from traits.etsconfig.api import ETSConfig

In [2]: ETSConfig.toolkit
Out[2]: ''
```

**Comment by corranwebster** [comment] 2017-08-04 16:26
To determine the backend, what version of TraitsUI are you using?  If >= 5 it will be PySide or PyQt, otherwise it will be WxPython.  To be sure, `import pyface.api` and then look at the value of `ETSConfig.toolkit`.

The Enthought brains trust is saying that `sys.getfilesysteminfo()` may be the root cause. @massich do you see the same effect with `import sys; sys.getfilesysteminfo()`.

**Comment by massich** [comment] 2017-08-04 16:34
now I get an answer for `ETSConfig.toolkit'
```sh
In [4]: ETSConfig.toolkit
Out[4]: 'qt4'
```
but there's no such `getfilesysteminfo` in sys

**Comment by corranwebster** [comment] 2017-08-04 16:34
@massich wrong function name ^^^ it should be `sys.getfilesystemencoding()`

**Comment by massich** [comment] 2017-08-04 16:35
@corranwebster ajajajaj I was searching for it everywhere. I thought it was me who lost it 

anyway, the encoding is
```sh
In [8]: sys.getfilesystemencoding()
Out[8]: 'UTF-8'
```

**Comment by corranwebster** [comment] 2017-08-04 16:36
@massich What do you see with
```
import locale
locale.nl_langinfo(locale.MON_1)
import sys; sys.getfilesystemencoding()
locale.nl_langinfo(locale.MON_1)
```

**Comment by massich** [comment] 2017-08-04 16:38
>To determine the backend, what version of TraitsUI are you using? If >= 5 it will be PySide or PyQt, otherwise it will be WxPython. To be sure, import pyface.api and then look at the value of ETSConfig.toolkit.

And the answer to this part, yes ` import pyface.api` also reproduce the error

**Comment by massich** [comment] 2017-08-04 16:39
```sh
In [1]: import locale
   ...: locale.nl_langinfo(locale.MON_1)
   ...: import sys; sys.getfilesystemencoding()
   ...: locale.nl_langinfo(locale.MON_1)
   ...: 
Out[1]: 'January'
```

**Comment by jorisvandenbossche** [comment] 2017-08-04 17:00
I can reproduce it by using PyQ4 as the backend. 

I created a fresh environment in which I installed `traitsui`. This installed PyQt5 by default, which was (I suppose) not used as a backend. Importing `traitsui.editors.enum_editor` then didn't affect my locale. 
However, when I downgraded PyQt to 4 in that environment, and ran the same test, then importing from traitsui *did* change my locale.

**Comment by massich** [comment] 2017-08-04 17:07
Indeed @jorisvandenbossche pyqt4 is the responsable. 

```sh
In [1]: import locale

In [2]: locale.nl_langinfo(locale.MON_1)
Out[2]: 'January'

In [3]: import pyface.api

In [4]: locale.nl_langinfo(locale.MON_1)
Out[4]: 'January'

In [7]: import traitsui.editors.enum_editor

In [8]: locale.nl_langinfo(locale.MON_1)
Out[8]: 'January'

In [9]: import PyQt5
```

**Comment by corranwebster** [comment] 2017-08-05 07:12
@massich Thanks.  I'm now suspicious of this code https://github.com/enthought/pyface/blob/master/pyface/qt/__init__.py#L22 which is only run with PyQt4.

What happens when you run:
```
import locale
print locale.nl_langinfo(locale.MON_1)
import sip
sip.setapi('QDate', 2)
sip.setapi('QDateTime', 2)
sip.setapi('QString', 2)
sip.setapi('QTextStream', 2)
sip.setapi('QTime', 2)
sip.setapi('QUrl', 2)
sip.setapi('QVariant', 2)
print locale.nl_langinfo(locale.MON_1)
```

**Comment by massich** [comment] 2017-08-07 08:32
@corranwebster Nop. I get `January` and `January`.

**Comment by corranwebster** [comment] 2017-08-07 09:22
I have to admit I am baffled by this one. I am far from an export on i18n, but it would seem that somewhere something is calling `setlocale` at least for `LC_TIME` and possibly for `LC_ALL` which would switch things from "C" locale to your environment settings (where `LC_TIME` is French).  However, I can't find any calls to `setlocale` in the ETS codebase.

This matplotlib issue seems like it may be related: https://github.com/matplotlib/matplotlib/issues/1867 If it is, you should see the same effect with something like:
```
import locale
print locale.nl_langinfo(locale.MON_1)
from PyQt4 import QtGui
app = QtGui.QApplication([])
print locale.nl_langinfo(locale.MON_1)
```

**Comment by massich** [comment] 2017-08-07 09:27
Yes. This reproduce the error:
```sh
January
janvier
```

**Comment by corranwebster** [comment] 2017-08-07 09:35
I also get something similar.
```
In [1]: import locale

In [2]: locale.getlocale()
Out[2]: (None, None)

In [3]: from PyQt4 import QtGui
In [4]: locale.getlocale()
Out[4]: (None, None)

In [5]: app = QtGui.QApplication([])
In [6]: locale.getlocale()
Out[6]: ('en_GB', 'UTF-8')
```

This pretty much confirms that Qt4 is at fault.  I'm going to close this issue, because I don't think there's anything we can do at the TraitsUI/Pyface level to fix this (starting an application is done as part of the toolkit selection process: if we can't start an app, then we don't want to use that toolkit). 

As a work-around you may be able to so something like grabbing the current locale before you import any GUI code, and then set the locale to the old value when you are done.

**Closed by corranwebster** 2017-08-07 09:35 UTC

**Comment by mdickinson** [comment] 2017-08-07 10:10
Related: https://stackoverflow.com/questions/25661295/why-does-qcoreapplication-call-setlocalelc-all-by-default-on-unix-linux
