### ISSUE TITLE
RGBColorEditor uses mapped value even when color isn't string

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traitsui#763] opened 2020-03-20 14:09 UTC
This is for Qt. I have not checked wx.

The [`RGBColorTrait`](https://github.com/enthought/traitsui/blob/277bd2a93006ab4d7a02e9ad6024bab190681976/traitsui/qt4/rgb_color_trait.py#L97-L100) allows both RGB tuples and strings, of which the latter is a mapped trait. This causes funny business because a direct assignment of an RGB tuple does not update the mapped value.

The [`RGBColorEditor` gives precedence](https://github.com/enthought/traitsui/blob/277bd2a93006ab4d7a02e9ad6024bab190681976/traitsui/qt4/rgb_color_editor.py#L42-L45) to the mapped trait, which causes situations like this:

```python
from traits.api import *
from traitsui.api import *


class Thing(HasTraits):
    color = RGBColorTrait()

    def _color_default(self):
        return (0.1, 0.2, 0.3)

    view = View(
        Item('color')
    )


t = Thing()
t.configure_traits()
```

![image](https://user-images.githubusercontent.com/1588456/77171418-72117800-6a8a-11ea-990b-e7c5fa7c3196.png)

The background color for the editor appears as white because the mapped `color_` is not synchronized to the unmapped value.

**Comment by ievacerny** [comment] 2020-05-19 19:39
The problem is with the handling of `*_default` method. It is fixed by https://github.com/enthought/traits/issues/1081 and should be in Traits 6.1 release. 

With an older Traits version the following examples set the background color as expected, so a simple workaround would be to avoid `_default` with `RGBColorTrait` and `ColorTrait`.
``` python
class Thing(HasTraits):
    color = RGBColorTrait()

    view = View(
        Item('color')
    )


t = Thing()
t.color = (0.1, 0.2, 0.3)
t.configure_traits()
```
``` python
class Thing(HasTraits):
    color = RGBColorTrait((0.1, 0.2, 0.3))

    view = View(
        Item('color')
    )


t = Thing()
t.configure_traits()
```

**Closed by ievacerny** 2020-05-19 19:39 UTC
Labels: ETS Backlog
