### ISSUE TITLE
Button appearance not being updated to match 'enabled_when' state

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#913] opened 2020-06-19 18:41 UTC
I'm seeing some strange behaviour using `enabled_when` with buttons: the button's behaviour matches the `enabled_when` setting, but the button's appearance does not (though a window resize or an application switch causes the button's appearance to be refreshed).

I'm fairly sure that this is a regression; this is cut down from a `traits_futures` example that used to work as expected, but now doesn't. Various things have changed, including Qt version, TraitsUI version, Traits version, macOS version, ... I'll see if I can track down which of these causes this regression.

Here's the example code. It sets up a pair of buttons, exactly one of which should be enabled at any given moment - it's supposed to be the interface to a (phantom) background process which is either running or idle. If it's idle, then the "start" button is enabled, and when pressed changes the state to "running". If it's running, then the "stop" button is enabled, and when pressed changes the state back to "idle".

```python
from traits.api import Bool, Button, Enum, Property
from traitsui.api import Handler, UItem, View


class BadButtons(Handler):
    state = Enum("idle", "running")

    start = Button()

    def _start_fired(self):
        self.state = "running"

    stop = Button()

    def _stop_fired(self):
        self.state = "idle"

    start_enabled = Property(Bool(), depends_on='state')

    def _get_start_enabled(self):
        return self.state == "idle"

    stop_enabled = Property(Bool(), depends_on='state')

    def _get_stop_enabled(self):
        return self.state == "running"

    def default_traits_view(self):
        return View(
            UItem('start', enabled_when='start_enabled'),
            UItem('stop', enabled_when='stop_enabled'),
            resizable=True,
        )


if __name__ == '__main__':
    view = BadButtons()
    view.configure_traits()
```

The UI works as expected: the buttons are enabled or disabled as expected, but the appearance does not update. Here's what it looks like on my machine just after hitting "start" for the first time:

<img width="184" alt="Screenshot 2020-06-19 at 19 40 34" src="https://user-images.githubusercontent.com/662003/85170087-c8967a00-b264-11ea-9f9b-f5d6fa0f0510.png">

At this point, the "stop" button should be enabled, and it is: it can be clicked, and that click has the expected effect. It just doesn't *look* enabled.

And after switching to a different application or back, or resizing the window, it has the expected appearance:

<img width="184" alt="Screenshot 2020-06-19 at 19 41 10" src="https://user-images.githubusercontent.com/662003/85170136-dc41e080-b264-11ea-9488-4c767eae9e24.png">

Possibly relevant package versions:
```
traitsui                       7.0.0-2
pyface                         7.0.0-3 
traits                         6.1.0-1 
pyqt5                          5.14.2-3
pyqt5_sip                      12.7.2-1
pytz                           2018.9-1
qt                             5.12.6-5
```
This is Python 3.6.10 on macOS 10.14.6.

**Comment by mdickinson** [comment] 2020-06-19 18:48
> I'll see if I can track down which of these causes this regression.

The significant change appears to be Qt4 to Qt5: with Qt4 this works as expected.

**Comment by kitchoi** [comment] 2020-06-19 18:52
The buttons work and look fine on Linux (Fedora 30), Python 3.8 and the following dependencies from PyPI:
```
Package    Version
---------- -------
configobj  5.0.6  
numpy      1.18.5 
pip        19.2.3 
pyface     7.0.0  
Pygments   2.6.1  
PySide2    5.15.0 
setuptools 41.2.0 
shiboken2  5.15.0 
six        1.15.0 
traits     6.1.0  
traitsui   7.0.0
```
I tried traitsui master too and it also works.

**Comment by mdickinson** [comment] 2020-06-19 18:57
Interesting; maybe it's macOS only? If we're _really_ lucky, it's macOS 10.14 only. What do you see on macOS 10.15?

I just checked with TraitsUI master (with the development environment created by `etstool.py`), and I see the same behaviour: works with PyQt4, fails with PyQt5.

**Comment by mdickinson** [comment] 2020-06-19 19:02
Looks like it might go all the way down to Qt: https://forum.qt.io/topic/107558/push-buttons-and-pixmaps-not-updating-refreshing-properly-in-pyqt-only-on-macos/7

**Comment by mdickinson** [comment] 2020-06-19 19:23
A workaround is to run `processEvents()` after every state change. Adding this code worked for me:

```
    def _state_changed(self):
        from pyface.qt.QtGui import QApplication
        app = QApplication.instance()
        app.processEvents()
```

**Comment by xamcost** [comment] 2020-06-25 17:26
Hi there !

@corranwebster recommended me to follow up on this issue, since we (the ms-platform team) encountered something similar. The situation is the following: you have a `TableEditor`, a `TextEditor` and a button. Suppose that you want to set the content of the `TextEditor` by getting the text of a selected element in the `TableEditor` by hitting the button: the text will not appear, unless you click on the `TextEditor`. As the case discussed in this issue, this happens **only** on Mac OS X (tested on 10.15.5, traits 6.1 (he he) and traitsui 7.0). The below code snippet reproduces the issue: 

```Python3
from traits.api import Button, HasTraits, Instance, List, Str
from traitsui.api import TableEditor, TextEditor, UItem, View
from traitsui.table_column import ObjectColumn


class Knight(HasTraits):

    name = Str()

    color = Str()


class Question(HasTraits):

    knights = List(Instance(Knight))

    color_picked = Str()

    color_button = Button('Color')

    selected_row = Instance(Knight)

    def _color_button_fired(self):

        self.color_picked = self.selected_row.color

    def default_traits_view(self):

        view = View(
            UItem('knights',
                  editor=TableEditor(
                      columns=[
                          ObjectColumn(name='name'),
                          ObjectColumn(name='color')
                      ],
                      selected='selected_row',
                  )),
            UItem('color_picked', editor=TextEditor()),
            UItem('color_button'),
        )
        return view


if __name__ == '__main__':
    view = Question(knights=[
        Knight(name='Galaad', color='red'),
        Knight(name='Arthur', color='blue'),
    ])
    view.configure_traits()
```

Please note that @mdickinson 's trick, namely adding the listener below, works. A big thanks for that !

```Python3
    def _color_picked_changed(self):

        from pyface.qt.QtGui import QApplication
        app = QApplication.instance()
        app.processEvents()
```

**Comment by kitchoi** [comment] 2020-06-25 17:32
>     def _color_picked_changed(self):
        from pyface.qt.QtGui import QApplication
        app = QApplication.instance()
        app.processEvents()

Would it be okay to use `pyface.api.GUI.process_events()` instead of calling it on `QApplication.instance()`?
`QApplication.instance()` can return `None` if the Qt application has not started (probably rare for your use case as `configure_traits()` would have created it for you. But you might run into issue if you try to test the method on its own.

**Comment by kitchoi** [comment] 2020-06-25 17:40
And if you have both `_color_picked_changed` and `_color_picked_fired` defined, the order of which method is called is not guaranteed. It would be better to combine them to ensure `process_events` is called in the order you need.

**Comment by xamcost** [comment] 2020-06-25 17:51
That's a great idea @kitchoi ! I tried putting `pyface.api.GUI.process_events()` inside `_color_button_fired()`, and remove `_color_picked_changed()`, and it works like a charm ! Thanks a lot :)

**Comment by xamcost** [comment] 2020-06-25 17:52
(_sorry.. why the close button is so close to comment...._)

**Comment by ievacerny** [comment] 2020-07-01 10:26
Because of this bug, `SetEditor` is practically unusable with pyqt5

**Comment by mdickinson** [comment] 2020-07-01 10:49
> `SetEditor` is practically unusable with pyqt5

That's unfortunate. I was hoping we could dismiss this bug as unlikely to occur on platforms we care about. But even if our customers are only on Linux and Windows, our developers are still developing on macOS, and this is going to impact them (causing them to spend time debugging).

One thing to check before we invest effort in implementing a workaround is whether the latest PyQt5 / Qt5 fixes this. (It probably doesn't, but I haven't checked.)

**Comment by mdickinson** [comment] 2020-07-01 10:58
> One thing to check before we invest effort in implementing a workaround is whether the latest PyQt5 / Qt5

This _does_ seem to be working as expected for me with PyQt 5.15 from PyPI. (Qt 5.15 is an LTS release, and the last one in the Qt 5 series, so it may make sense to ask the buildsystem to upgrade.)

**Comment by mdickinson** [comment] 2020-07-01 11:02
@ievacerny Could you check whether upgrading to PyQt 5.15 fixes the `SetEditor` issues?

**Comment by ievacerny** [comment] 2020-07-01 11:13
> @ievacerny Could you check whether upgrading to PyQt 5.15 fixes the `SetEditor` issues?

I don't see any change compared to PyQt 5.14, `SetEditor` is still broken (tested using `Standard_Editors/SetEditor_demo.py`)

**Comment by mdickinson** [comment] 2020-07-01 11:21
Thanks. To be clear, is the form of the `SetEditor` breakage the same as in this issue: i.e., the issue is purely cosmetic - the UI widget appearance is misleading, but the widgets function as expected?

**Comment by ievacerny** [comment] 2020-07-01 11:23
The issue is a combination of buttons appearing as enabled even though they are not and text fields not updating upon change. The underlying values are updating as expected.

**Comment by kitchoi** [comment] 2020-07-02 13:14
For reference, the `SetEditor` (tested using `Standard_Editors/SetEditor_demo.py`) works fine on a **Linux** machine (Fedora 30) and the following dependency:
```
Package    Version
---------- -------
packaging  20.4
pip        20.1.1
pyface     7.0.0
pyparsing  2.4.7
PyQt5      5.15.0
PyQt5-sip  12.8.0
setuptools 41.2.0
sip        5.3.0
six        1.15.0
toml       0.10.1
traits     6.1.0
traitsui   7.0.0
```
(I tested traitsui master, and Python 3.6, same.)
The buttons enable/disable states are as expected, the text fields are updated as expected.

**Comment by kitchoi** [comment] 2020-07-02 13:16
I tried downgrading to `PyQt5 5.14.2` on the same Linux machine, also no such issues.

**Comment by ievacerny** [comment] 2020-07-27 16:52
We're running into this (or #928 related) bug in our project. We have a button that updates a `TabularEditor` but the update doesn't take effect until users click on the table, which normally they wouldn't do at all. 

Relevant package versions (Python 3.6.5):
```
pyface                        7.0.0
PyQt5                         5.14.2
PyQt5-sip                     12.7.2
Qt                            5.12.6
traits                        6.1.0
traitsui                      7.0.0
```

I tried to write a minimal working example (see my attempt below) but couldn't reproduce the exact behavior. In our case one click anywhere on the table updates everything. With the minimal working example more clicks are needed and behavior feels even more broken. 

We tried to use suggested workaround in our `_changed` methods but that didn't change anything. Upgrading to PyQt5 5.15 didn't help either. Issue doesn't happen with PyQt4 or on Linux (as far as I know).

<details>
<summary> Minimal working example </summary>

```
from traits.api import Any, Button, Event, HasTraits, List, Str
from traitsui.api import TabularAdapter, TabularEditor, UItem, View


class PartialAlphabet(HasTraits):

    sequence = Str()

    def __getitem__(self, key):
        return self.sequence[key]

    def __len__(self):
        return len(self.sequence)

    def make_uppercase(self):
        self.sequence = self.sequence.upper()


class MinimalExample(HasTraits):

    displayed_data = List(Any)

    uppercase_data = Button("Make uppercase")

    update_table = Event

    def default_traits_view(self):
        return View(
            UItem('uppercase_data'),
            UItem(
                'displayed_data',
                editor=TabularEditor(
                    adapter=TabularAdapter(columns=['0', '1', '2', '3', '4']),
                    refresh='update_table',
                    stretch_last_section=False,
                )
            )
        )

    def _uppercase_data_changed(self):
        for seq in self.displayed_data:
            seq.make_uppercase()
        self.update_table = True


demo = MinimalExample(
    displayed_data=[
        PartialAlphabet(sequence="abcde"),
        PartialAlphabet(sequence="bcdef"),
        PartialAlphabet(sequence="cdefg"),
    ]
)
demo.configure_traits()

```

</details>

**Comment by kitchoi** [comment] 2020-07-31 08:24
For those coming across this trying to find the workaround, please consider the toolkit agnostic `GUI` over calling the Qt method directly. IOW, this being the workaround:
```
    def _stop_fired(self):
        from pyface.api import GUI
        GUI().process_events()
        self.state = "idle"
```
The workaround is really not scalable, and I'd hope we don't have to do all over the place.

**Comment by kitchoi** [comment] 2020-07-31 08:26
@ievacerny Thank you for the new report and example! Just wanted to clarify, when you said:

> Upgrading to PyQt5 5.15 didn't help either.

Was the Qt version also upgraded? Or was it still 5.12.6?

**Comment by ievacerny** [comment] 2020-07-31 08:37
> @ievacerny Thank you for the new report and example! Just wanted to clarify, when you said:
> 
> > Upgrading to PyQt5 5.15 didn't help either.
> 
> Was the Qt version also upgraded? Or was it still 5.12.6?

No, it remained 5.12.6 after PyQt5 5.15 upgrade

**Comment by kitchoi** [comment] 2020-10-05 10:39
I can no longer reproduce this issue on OSX 10.15.5 and PySide2 5.15.1, Python 3.8
Dependencies:
```
Package    Version     
---------- ------------
pip        19.2.3      
pyface     7.0.1       
PySide2    5.15.1      
setuptools 41.2.0      
shiboken2  5.15.1      
traits     6.1.1       
traitsui   7.1.0.dev367
```

In fact, neither could I reproduce it with traitsui 7.0.1.

For reference, there are a few Qt Bugs reported surrounding widgets not being repainted when it should in response to a slot attached to a QPushButton clicked signal:

https://bugreports.qt.io/browse/QTBUG-68067
https://bugreports.qt.io/browse/QTBUG-68740
https://bugreports.qt.io/browse/QTBUG-68521

Other issues with similarly looking repainting issues may share the same underlying cause, or they may not be, but there are separate issues opened for those. See for example:
#928 
#1245 

@mdickinson On the basis that the reported issue is now resolved by upgrading PySide2, should we close this issue?

**Comment by mdickinson** [comment] 2020-10-05 13:27
@kitchoi The originally reported issue is indeed solved with recent package versions. I'd say go ahead and close this, except that various other, possibly different, issues have been reported in this thread, and I don't know their status. It'll probably take some work to test each one and create new issues as necessary. (cue rant on keeping GitHub issues focused on a single issue ...)

**Comment by kitchoi** [comment] 2020-10-05 14:05
Thanks. Closing.

**Closed by kitchoi** 2020-10-05 14:05 UTC
Labels: type: bug
