### ISSUE TITLE
TextEditor's `invalid` parameter breaks synchronisation between trait and its displayed value

### ISSUE THREAD

**Issue by peterzahemszky** [enthought/traitsui#1567] opened 2021-03-31 17:27 UTC
Using the `invalid` parameter of `TextEditor` sometimes breaks the synchronisation between the attribute being edited and its displayed value.

```python
from traits.api import *
from traitsui.api import *


class Model(HasTraits):

    my_constant = Bool(False)

    main_text = Str()

    shadow_text = Str()

    @observe('main_text')
    def update_shadow_text(self, _event):
        self.shadow_text = self.main_text

    @observe('shadow_text')
    def report_shadow_text_changed(self, _event):
        print('shadow text changed to', self.shadow_text)


class ViewModel(ModelView):

    model = Instance(Model)

    def default_traits_view(self):
        editor = TextEditor(invalid='my_constant')
        editor2 = TextEditor()

        return View(
            Item('model.main_text'),
            Item('model.shadow_text', editor=editor),
        )


if __name__ == '__main__':
    model = Model()
    viewmodel = ViewModel(model=model)
    viewmodel.configure_traits()
```

To reproduce, run the example code above, and perform the following steps:
- In the top text box, insert the string "asd" character by character,
- observe that on each key stroke a line appears on the command line ("shadow text changed to ..."),
- verify that the bottom text box does not display the same text as the top one.

I would expect the bottom text box to display the same text as the top one, because of the presence of the method called `listener`.

In fact, when the following patch is applied to the code snippet above:
```patch
-            UItem('model.shadow_text', editor=editor),
+            UItem('model.shadow_text', editor=editor2),
```
(that is, `TextEditor` is used _without_ its `invalid` parameter), the behaviour upon re-run is as expected: the string in the bottom text box is tracking the top one.

**Comment by aaronayres35** [comment] 2021-03-31 19:05
Thank you for the report and for the example code to reproduce the issue!
I am able to reproduce this locally

**Comment by aaronayres35** [comment] 2021-03-31 19:43
After messing around a little more, I believe that this applies to more than just the text editor:
eg if I do 
```
from traits.api import *
from traitsui.api import *


class Model(HasTraits):
    my_constant = Bool(False)
    main_text = Enum('a', 'b')
    shadow_text = Enum('a', 'b')

    @observe('main_text')
    def update_shadow_text(self, _event):
        self.shadow_text = _event.new


class ViewModel(ModelView):
    model = Instance(Model)

    def default_traits_view(self):
        return View(
            Item('model.main_text'),
            Item(
                'model.shadow_text',
                editor=EnumEditor(
                    values=['a','b'],
                    invalid='my_constant'
                )
            ),
        )


if __name__ == '__main__':
    model = Model()
    viewmodel = ViewModel(model=model)
    viewmodel.configure_traits()
```
and change the selection of the first combobox, the traits are out of sync, but if I remove the line `invalid='my_constant'` they stay synced

**Comment by aaronayres35** [comment] 2021-03-31 19:57
Looks like the following segment of code is swallowing an error:
https://github.com/enthought/traitsui/blob/1c880889f19abbda50deddd497f7a24721b3a13a/traitsui/editor.py#L393-L395

removing the `with self.raise_to_debug()` and running your given example I see:
<details>

```
Traceback (most recent call last):
  File "traitsui/junk/thingy.py", line 74, in <module>
    viewmodel.configure_traits()
  File "/Users/aayres/Desktop/traitsui/traitsui/handler.py", line 470, in configure_traits
    **args
  File "/Users/aayres/Desktop/traits/traits/has_traits.py", line 2095, in configure_traits
    args,
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/toolkit.py", line 243, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/view_application.py", line 94, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/view_application.py", line 136, in __init__
    args=self.args,
  File "/Users/aayres/Desktop/traitsui/traitsui/view.py", line 455, in ui
    ui.ui(parent, kind)
  File "/Users/aayres/Desktop/traitsui/traitsui/ui.py", line 237, in ui
    self.rebuild(self, parent)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/toolkit.py", line 173, in ui_live
    ui_live.ui_live(ui, parent)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_live.py", line 53, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_live.py", line 75, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_base.py", line 298, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_live.py", line 235, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 273, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 631, in __init__
    layout = self._add_items(content, inner)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 897, in _add_items
    ui, object, name, item.tooltip, None
  File "/Users/aayres/Desktop/traitsui/traitsui/editor_factory.py", line 125, in simple_editor
    description=description,
  File "/Users/aayres/Desktop/traitsui/traitsui/editor.py", line 541, in __init__
    self.sync_value(self.factory.invalid, "invalid", "from")
  File "/Users/aayres/Desktop/traitsui/traitsui/editor.py", line 387, in sync_value
    user_value = xgetattr(user_object, xuser_name)
  File "/Users/aayres/Desktop/traits/traits/trait_base.py", line 322, in xgetattr
    return getattr(object, names[-1])
AttributeError: 'ViewModel' object has no attribute 'my_constant'
```

</details>

It looks like its looking for `my_constant` on the `ViewModel` object not on the `Model`.
if I replace the `editor = TextEditor(invalid='my_constant')` line in your example with `editor = TextEditor(invalid='model.my_constant')` things seem to work as expected.

@peterzahemszky does making this change resolve your issue?

**Comment by peterzahemszky** [comment] 2021-04-01 12:57
Thank you for the quick reply!

In our production code the `my_constant` trait was an attribute of the `ViewModel` class (and the synchronisation was still missing). However, changing the `invalid` parameter from `my_constant` to `handler.my_constant` fixed this.

**Comment by aaronayres35** [comment] 2021-04-01 13:29
> Thank you for the quick reply!
> 
> In our production code the `my_constant` trait was an attribute of the `ViewModel` class (and the synchronisation was still missing). However, changing the `invalid` parameter from `my_constant` to `handler.my_constant` fixed this.

Ah I see, that makes sense.  Glad we were able to get this resolved! I'm going to close this issue now as I believe there is no required traitsui change that needs to be made here.  Thanks again for the detailed issue!

**Closed by aaronayres35** 2021-04-01 13:29 UTC
