### ISSUE TITLE
ListEditor broken in 4.4

### ISSUE THREAD

**Issue by jf---** [enthought/traitsui#148] opened 2013-12-27 21:20 UTC
The latest release breaks the ListEditor.
No context menu shows up, when the button on a list item is pressed

( PyQt 4.10, OSX )

**Comment by aestrivex** [comment] 2015-04-07 05:21
This bug seems to be due some changes in traitsui 4.4 which fixed a longstanding bug (#109) where the ListEditor button did not click in pyside, and simultaneously introduced a regression in pyqt. Reverting this change on a local installation fixes the problem.

I understand very little about why the signals are connected correctly on pyside and not on pyqt, maybe someone who understands more about toolkit code can provide a more comprehensive fix.

**Comment by petrushy** [comment] 2015-06-07 09:00
The list editor works for me in 4.3.0, not in 4.4.0 (pyqt). I think this is the link to the patch where things are changed:

https://github.com/enthought/traitsui/commit/7d1939466c1cdc15afb5fea83eb3c9f5deb1f7cc?diff=split

**Comment by aestrivex** [comment] 2015-06-07 14:57
If anyone wants to use it, I created this workaround for my program

https://gist.github.com/aestrivex/3a8608f3f26faa9e8817

This file defines a CustomListEditor class which has the same behavior as ListEditor except for the two lines of code which checks the qt_api variable in pyface.api and use the two different code segments present in the 4.3 and 4.4, depending on the current backend.

It's a bandage but it works

**Comment by petrushy** [comment] 2015-06-07 15:25
Thank you, saving that gist as a module custom_list_editor.py and importing the CustomListEditor as editor class worked great!

**Comment by corranwebster** [comment] 2017-01-17 11:22
This issue appears to be resolved by #330

**Closed by corranwebster** 2017-01-17 11:22 UTC
