### ISSUE TITLE
TraitError on UI dispose

### ISSUE THREAD

**Issue by pyhannes** [enthought/traitsui#1805] opened 2022-02-05 23:19 UTC
Hey,

i have a weird error which i cannot always reproduce, but here is the error traceback that happens
when i try to close the PyFace GUI.

```
Traceback (most recent call last):
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\pyface\ui\qt4\gui.py", line 176, in event
    self._callable(*self._args, **self._kw)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\pyface\i_window.py", line 233, in close
    self.destroy()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\pyface\tasks\task_window.py", line 101, in destroy
    self._destroy_state(state)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\pyface\tasks\task_window.py", line 371, in _destroy_state
    state.central_pane.destroy()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\pyface\tasks\traits_task_pane.py", line 55, in destroy
    self.ui.dispose()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 256, in dispose
    self.finish()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 278, in finish
    self.reset(destroy=False)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 315, in reset
    editor.dispose()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\tree_editor.py", line 257, in dispose
    self._delete_node(self._tree.invisibleRootItem())
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\tree_editor.py", line 428, in _delete_node
    self._delete_node(cnid)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\tree_editor.py", line 428, in _delete_node
    self._delete_node(cnid)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\tree_editor.py", line 428, in _delete_node
    self._delete_node(cnid)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\tree_editor.py", line 465, in _delete_node
    self._clear_editor()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\tree_editor.py", line 775, in _clear_editor
    editor._node_ui.dispose()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 256, in dispose
    self.finish()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 278, in finish
    self.reset(destroy=False)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 315, in reset
    editor.dispose()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\list_editor.py", line 634, in dispose
    self.close_all()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\list_editor.py", line 620, in close_all
    ui.dispose()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 253, in dispose
    self.save_prefs()
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 544, in save_prefs
    toolkit().save_window(self)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\toolkit.py", line 338, in save_window
    helper.save_window(ui)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\qt4\helper.py", line 147, in save_window
    ui.save_prefs((geom.x(), geom.y(), geom.width(), geom.height()))
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 551, in save_prefs
    db[id] = self.get_prefs(prefs)
  File "C:\Python38\lib\shelve.py", line 124, in __setitem__
    p.dump(value)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traits\has_traits.py", line 1390, in __reduce_ex__
    return (__newobj__, (self.__class__,), self.__getstate__())
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traits\has_traits.py", line 1354, in __getstate__
    result = self.trait_get(transient=is_none)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traits\has_traits.py", line 1467, in trait_get
    value = getattr(self, name, missing)
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traits\trait_list_object.py", line 580, in __init__
    self._validate_length(len(value))
  File "C:\git\teeh\.tox\py38-dev\lib\site-packages\traits\trait_list_object.py", line 890, in _validate_length
    raise TraitError(
traits.trait_errors.TraitError: The 'bindings' trait of a KeyBindings instance must be a list of from 1 to 1 items which are a KeyBinding or None, but you attempted to change its length to 0 elements.
```

Win 10
traits==6.3.2
traits-futures==0.3.1
traits-stubs==6.1.0
traitsui==7.2.1
pyface==7.3.0

**Comment by mdickinson** [comment] 2022-02-07 08:50
@pyhannes Thanks for the report. I'm transferring this issue to the TraitsUI repository, since that's likely where we need to begin the investigation.

If you have code that reproduces the issue, that would likely speed up the investigation substantially.

**Comment by pyhannes** [comment] 2022-02-07 11:53
@mdickinson I will try, but this error seems to occur very randomly when i close the UI. Found no way yet to reproduce it, but it's occurring frequently.

**Comment by corranwebster** [comment] 2022-02-15 09:56
Something weird is happening with this list trait:
https://github.com/enthought/traitsui/blob/0b91536b4da95d24d986cf32a12086111df92db1/traitsui/key_bindings.py#L88-L89

As an immediate thing, I think this should probably be changed to `List(Instance(Binding))`, but why this trait is being treated as if it has to be a list of length 1 I don't know, nor why it is being initialized during state serialization in a `shelve` operation.

Ah - this would be the problem:
https://github.com/enthought/traitsui/blob/0b91536b4da95d24d986cf32a12086111df92db1/traitsui/key_bindings.py#L264

**Comment by corranwebster** [comment] 2022-02-15 09:58
And this: https://github.com/enthought/traitsui/blob/0b91536b4da95d24d986cf32a12086111df92db1/traitsui/key_bindings.py#L147-L150

No idea what the original intent was.

**Comment by corranwebster** [comment] 2022-02-15 10:13
OK.  I think I understand what the intent was.

Each `KeyBindings` object is associated with a UI and has certain methods and traits from that are exposed to be bound to keys.  These bindings are supposed to be user-editable, but there are only a fixed number of possibilities, and we don't want the user to be able to add or remove from the list.  So way back in the day (Traits 2 era, by the history) the solution was to work out what the length of the list is and create a new trait which forced the length to stay fixed.

Of course that creates a problem when you add or remove keybindings in other ways, coupled with the fact that these are saved as preferences.

The correct behaviour is that the key binding class shouldn't care about the length of the list, and the editor should prevent adding or removing from the list (I think `style="readonly"` will do this).  There is a bigger problem of how to handle new versions of the code which change the number of exposed keybindings, which needs some thought.

@pyhannes An immediate workaround for you might be to find where TraitsUI and Pyface are storing their preferences (usually a hidden directory named after the application, or `.enthought` or similar) and remove all the traitsui and pyface preferences

**Comment by pyhannes** [comment] 2022-02-15 10:39
@corranwebster Thanks for the hint ;) Let's see if it happens again.

**Comment by corranwebster** [comment] 2022-02-15 10:48
> There is a bigger problem of how to handle new versions of the code which change the number of exposed keybindings, which needs some thought.

This is handled here: https://github.com/enthought/traitsui/blob/0b91536b4da95d24d986cf32a12086111df92db1/traitsui/ui.py#L530

**Closed** 2022-02-18 13:54 UTC
