### ISSUE TITLE
Resizeable windows opened with edit_traits() are forced to the background

### ISSUE THREAD

**Issue by mswiggers** [enthought/traitsui#1078] opened 2020-07-28 11:21 UTC
Hello everyone,

Since the latest update (TraitsUI 7.0.1-1), I have noticed what I think is unwanted behaviour.

Whenever I open a second window with the `edit_traits()` function, and the resizable property of this View is set to True, the window is hidden behind the first window (which was called through `configure_traits()`).

Below is a demo case. Try opening a second window through the menu bar of the 'Main' window, this should trigger the bug. I am using PyQt5:

```
from traitsui.api import Handler, View, Item
from traits.api import HasTraits, String, Int
from traitsui.menu import Menu, Action, CloseAction, MenuBar

the_action = Action(
    name = "Open a window",
    action = "_do_something"
)

class Sub(HasTraits):
    a_trait = Int
    
    def default_traits_view(self):
        return View(
            Item("a_trait"),
            resizable = True
        )
    
class DemoHandler(Handler):
    def _do_something(self, uiinfo):
        sub_window = Sub()
        sub_window.edit_traits()

class Main(HasTraits):
    name = String

    traits_view = View(
        Item("name"),
        menubar = MenuBar(
            Menu(
                the_action,
                name = "A menu"
            )
        ),
        handler = DemoHandler()
    )

main = Main()
main.configure_traits()
```

Kind regards,

Matthias

**Comment by rahulporuri** [comment] 2020-07-28 11:56
@mswiggers thank you for adding a script to reproduce the issue you are encountering. I just have a couple of more questions/clarifications.

What OS are you seeing this issue on and what version of PyQt5 are you working with?
What exactly do you mean by "... forced to the background" and "... is hidden behind the first window"?

I was able to run the code you provided on Win 10 PyQt5 5.14.2-3 and cpython 3.6.0+12 64 bit. Here is what I see when i run the script and launch the secondary window via the menu item.

![bug-reproduce](https://user-images.githubusercontent.com/1926457/88662183-1eaed680-d0c9-11ea-879f-e24bda359932.PNG)

**Comment by mswiggers** [comment] 2020-07-28 12:26
Hi @rahulporuri ,

Sorry, I should have added this 🙂 . I am using CentOS Linux release 7.6.1810. The problem indeed doesn't seem to occur in your case.

What I mean is that the main window always stays in front of the secondary window, even when the secondary one. The only option for me is to drag the main window away, such that I can see the secondary one. I have added a screenshot below.

![image](https://user-images.githubusercontent.com/1809701/88665068-53795880-d0de-11ea-9766-717443c59e57.png)

**Comment by kitchoi** [comment] 2020-07-29 11:14
Hi @mswiggers 
Thank you for the report.
I can confirm the behaviour on a Linux machine, but not on Mac OSX machine nor a Windows machine. The X11 peculiarities documented [here](https://doc.qt.io/qt-5/application-windows.html#x11-peculiarities) looks relevant. Essentially all Qt (and TraitsUI) can do is to send hints to the window manager to request windows to be shown in certain ways - it is still up to the window manager whether to obey it.

In this case, TraitsUI should ensure the window flag (a hint) is set to `Qt.Dialog` for the second window. It does not do that for a resizable window and that is a bug. But after fixing that, we still cannot ensure the second window will be created on top of the first one due to the X11 peculiarities mentioned above.

**Comment by kitchoi** [comment] 2020-07-29 13:05
Orthogonal to the issue: If it makes sense in your use case, you might also want to consider setting the `parent` in `edit_traits` in the above example like this
```
class DemoHandler(Handler):
    def _do_something(self, uiinfo):
        sub_window = Sub()
        sub_window.edit_traits(parent=uiinfo.ui.control)
```
This tells Qt that the sub-window has a parent window: the UI created from `main.configure_traits()`, so that rather than treating the two windows as independent top-level windows, they are related to each other. For example, this will allow the sub-window to be closed as well when the parent UI from `main.configure_traits()` is closed by the user. However this does not fix the reported unexpected behaviour regarding the window relative positions.

**Closed** 2020-08-03 13:00 UTC
