### ISSUE TITLE
Spring items break pickling with Traits 5.0.0

### ISSUE THREAD

**Issue by FedeMiorelli** [enthought/traitsui#514] opened 2019-03-11 09:55 UTC
I encountered a strange behaviour while pickling traits with Traits 5.0.0 and Traitsui 6.0.0

If one trait contains an instance of another trait, whose view contains a Spring item, pickling results in an error.

In the following code, if one comments out the spring item in the view of the MyTrait the code works correctly, otherwise results in an error.

Most likely related to: [https://github.com/enthought/traits/issues/447](https://github.com/enthought/traits/issues/447)

```


import pickle

from traits.api import HasStrictTraits, Str, Instance
from traitsui.api import View, Group, Item, InstanceEditor, spring

class MyTrait(HasStrictTraits):
    MyString = Str
    
    traits_view = View(Group(Item('MyString'), spring))   # If spring is removed, this code runs OK


class MySecondTrait(HasStrictTraits):
    MyFirst = Instance(MyTrait)
    
    
    def save(self):
        with open('test.dump', 'wb') as fid:
            st = self.__getstate__()
            pickle.dump(st, fid, protocol=2)
        
    def load(self):
        with open('test.dump', 'rb') as fid:
            self.__setstate__(pickle.load(fid))
        
    
    traits_view = View(Group(Item('MyFirst', editor=InstanceEditor(editable=True), style='custom'), show_labels=False), buttons=['OK'])
    
    
m0 = MyTrait(MyString='test')
m1 = MySecondTrait(MyFirst=m0)

m1.configure_traits()
m1.save()


m2 = MySecondTrait()
m2.load()
print(m2.MyFirst.MyString)

```

Expected output:

```
test
```

Error 
```

Traceback (most recent call last):
  File "D:\Temp\testpickle.py", line 46, in <module>
    m1.save()
  File "D:\Temp\testpickle.py", line 31, in save
    pickle.dump(st, fid, protocol=2)
_pickle.PicklingError: Can't pickle <class 'traits.trait_types.Disallow'>: it's not the same object as traits.trait_types.Disallow
```

**Comment by corranwebster** [comment] 2019-03-11 10:02
Hi, thanks for the report.  This looks like it is related to https://github.com/enthought/traits/issues/452

The immediate workaround would be to downgrade your version of Traits to 4.6.0 (or github master prior to 23rd Dec 2018/commit eecc23d6 if there are bugfixes you need).

**Comment by corranwebster** [comment] 2019-03-11 10:03
I'm going to tentatively close the issue for now, since it is a duplicate of 
https://github.com/enthought/traits/issues/452 but please feel free to re-open if you think that the two issues are unrelated.

**Closed by corranwebster** 2019-03-11 10:03 UTC

**Comment by FedeMiorelli** [comment] 2019-03-11 10:04
Forgot to mention I am running Python 3.7.1 on Windows 10 64bit.
Not sure if this warrants re-opening as the other issue refers to Python 2 explicitly?

Thank you

**Comment by corranwebster** [comment] 2019-03-11 10:08
If you still see the issue with Traits 4.6.0 please re-open the ticket.  If not, maybe add your observations to the traits issue as an extra data point.

**Comment by mdickinson** [comment] 2019-03-11 10:12
Hmm. On closer inspection, this does look like a new variant of enthought/traits#452. It's not clear to me whether it should be a separate issue or not.

**Comment by FedeMiorelli** [comment] 2019-03-11 10:14
The issue is not present with v4.6.0, it appeared after update to 5.0.0

I leave up to you whether you'd like to re-open this or merge it with https://github.com/enthought/traits/issues/452

Thanks!

**Comment by mdickinson** [comment] 2019-03-11 10:23
So it's almost certainly a Traits issue rather than a Traits UI one - let's leave it closed here. I'll try to find time to investigate on the Traits side soon, and if necessary I'll split #452 into two issues then.

Thanks for the report!
