### ISSUE TITLE
"custom" style causes enum_editor to fail in python3 via bad indexing

### ISSUE THREAD

**Issue by deniederhut** [enthought/traitsui#336] opened 2017-02-02 16:57 UTC
| package | version |
| ------- | ------- |
| python  | 3.5.2  |
| traits | 4.6.0  |
| traitsui | 5.1.0 |

Given the following MRE:

```python
from traits.api import HasTraits, Enum
from traitsui.api import View, Item

class Burger(HasTraits):

    patties = Enum(1, 2)
    traits_view = View(Item('patties', style='custom'))


if __name__ == "__main__":
    burger = Burger()
    burger.configure_traits()
```

traitsui fails by trying to index with floats instead of integers, see traceback:

```
Traceback (most recent call last):
  File "tmp.py", line 16, in <module>
    burger.configure_traits()
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traits/has_traits.py", line 2172, in configure_traits
    kind, handler, id, scrollable, args )
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/toolkit.py", line 213, in view_application
    id, scrollable, args )
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/view_application.py", line 83, in view_application
    scrollable, args ).ui.result
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/view_application.py", line 134, in __init__
    args       = self.args )
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/ui.py", line 222, in ui
    self.rebuild( self, parent )
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/toolkit.py", line 155, in ui_live
    ui_live.ui_live( ui, parent )
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/ui_live.py", line 39, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/ui_live.py", line 59, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/ui_base.py", line 482, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/ui_live.py", line 177, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 255, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 592, in __init__
    layout = self._add_items(content, inner)
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/ui_panel.py", line 860, in _add_items
    editor.prepare(inner)
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/editor.py", line 156, in prepare
    self.init( parent )
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/enum_editor.py", line 369, in init
    self.rebuild_editor()
  File "/Users/dniederhut/anaconda3/envs/py35/lib/python3.5/site-packages/traitsui/qt4/enum_editor.py", line 433, in rebuild_editor
    name = names[index]
TypeError: list indices must be integers or slices, not float
```

**Comment by corranwebster** [comment] 2017-02-02 17:01
I think this is a duplicate of #306 and fixed by #311

**Closed** 2017-08-24 12:48 UTC
