### ISSUE TITLE
items tutorial causes bus error

### ISSUE THREAD

**Issue by cfarrow** [enthought/traitsui#3] opened 2011-06-16 18:01 UTC
The tutorial entitled Extended Traits UI Item and Editor References causes a bus error when run from the tutor application.
This is running all of ETS from the master on OSX 10.6.

Start tutor.py under traitsui/examples/tutorials and click on the mentioned tutorial.

**Comment by rahulporuri** [comment] 2021-04-27 04:27
Closing as I can't reproduce this at the moment. FTR, the example is https://github.com/enthought/traitsui/blob/master/examples/tutorials/traitsui_4.0/items.py

**Closed by rahulporuri** 2021-04-27 04:27 UTC
Labels: component: examples
