### ISSUE TITLE
Missing entry from application schema dict for etsdemo application

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traitsui#1039] opened 2020-07-21 09:51 UTC
The eam documentation mentions the need for a `"default"` key in the schema dictionary when the schema version is 2, which is what we are using. At the moment, not having this key is preventing eam from working as expected - https://docs.enthought.com/eam/metadata_schema.html#version-2

https://github.com/enthought/traitsui/blob/4594aaa9430c64e96dbb1313b123739c22631473/ets-demo/etsdemo/info.py#L20-L35

**Comment by kitchoi** [comment] 2020-07-21 09:56
The problematic behaviour is the following:
```
# In the environment where `etsdemo` and `eam` are installed
$ eam configure
Error: No default application registered in the environment
 Use --debug to show the traceback
```
I haven't checked what the expected behaviour should be.

**Comment by kitchoi** [comment] 2020-07-21 09:58
Note that we do have a test for compatibility with `eam`:
https://github.com/enthought/traitsui/blob/4594aaa9430c64e96dbb1313b123739c22631473/ets-demo/etsdemo/tests/test_info.py#L30-L36

A similar test can be added for `eam configure`?

**Comment by rahulporuri** [comment] 2020-07-21 10:05
> A similar test can be added for eam configure?

Yes. The PR that fixes this issue would ideally also add the test.

**Comment by kitchoi** [comment] 2020-07-21 10:59
Looks like the default key is optional.
Now I am not sure if enforcing it to true is really the right thing to do. 
If more than one distribution has set the default flag to true, one gets an error from `eam configure` and `eam start` again.
I am not sure we have a clear use case for supporting `eam configure` and `eam start` (and others) which requires a single application in the environment.

**Comment by rahulporuri** [comment] 2020-07-21 11:12
If we don't want to set default to True, I think it will be good to document this fact and mention that the user/dev will need to do `eam configure --name etsdemo` explicitly to configure/create shortcut/etc.

**Comment by kitchoi** [comment] 2020-07-21 11:13
Ah I was about to comment that one can run `eam configure --name etsdemo`.
This seems like documentation for `eam` though... e.g. I can find out I could run this command via reading more carefully the help message of `eam`. I don't think we need to duplicate that documentation, plus I don't think many people will be running the application via `eam` directly...

**Comment by kitchoi** [comment] 2020-07-21 13:05
Since we are not going to set the default flag, could we close this issue?

**Closed** 2020-07-21 13:32 UTC
Labels: difficulty: easy
